name: Deploy terriajs-app

on:
  workflow_dispatch:
    inputs:
      ref:
        description: "The branch or ref to deploy"
        required: true
        default: "main"

env:
  AWS_DEFAULT_REGION: ap-southeast-2
  ACTIONS_RUNNER_POD_NAME: k8-dtv-terria-single-v9mmg-xdzfs
  ACTIONS_RUNNER_REQUIRE_JOB_CONTAINER: true

jobs:
  preamble:
    runs-on: [self-hosted, linux]
    container:
      image: bitnami/kubectl
    steps:
      - name: set kubeconfig
        run: echo -n '${{ secrets.KUBECONFIG }}' | base64 --decode > /tmp/config

      - name: Check namespace
        #run: kubectl create namespace dtvutilities-terria --dry-run=client -o yaml | kubectl apply -f -
        run: kubectl create namespace dtvutilities-terria
        #env:
        #  KUBECONFIG: ${{ secrets.KUBECONFIG }}

  deployment:
    runs-on: [self-hosted, linux]
    container:
      image: alpine/helm
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.ref }}

      - name: set kubeconfig
        run: echo -n '${{ secrets.KUBECONFIG }}' | base64 --decode > /tmp/config

      - name: Update Dependencies
        uses: WyriHaximus/github-action-helm3@v2
        with:
          exec: helm dependency update deploy/helm/terria

      - name: 'Deploy'
        uses: WyriHaximus/github-action-helm3@v2
        with:
          exec: helm upgrade --namespace dtvutilities-terria --install --timeout 9999s terria deploy/helm/terria -f deploy/helm/wsp-deploy-test.yml --set "terriamap.image.full=940728446396.dkr.ecr.ap-southeast-2.amazonaws.com/terria-test:${GITHUB_SHA::8}"
        #  kubeconfig: '${{ secrets.KUBECONFIG }}'