name: Deploy terriajs-app

on:
  workflow_dispatch:
    inputs:
      ref:
        description: "The branch or ref to deploy"
        required: true
        default: "main"

env:
  AWS_DEFAULT_REGION: ap-southeast-2
  ACTIONS_RUNNER_POD_NAME: k8-dtv-terria-single-v9mmg-xdzfs
  ACTIONS_RUNNER_REQUIRE_JOB_CONTAINER: true

jobs:
  deployment:
    runs-on: [self-hosted, linux]
    container:
      image: bitnami/kubectl
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.ref }}

      - name: Misc
        run: kubectl version

#      - name: Update Dependencies
#        run:  helm dependency update deploy/helm/terria
#
#      - name: 'Deploy'
#        run: helm upgrade --namespace terria --install --timeout 9999s terria deploy/helm/terria -f deploy/helm/wsp-deploy-test.yml --set "terriamap.image.full=940728446396.dkr.ecr.ap-southeast-2.amazonaws.com/terria-test:${GITHUB_SHA::8}"
